select * from customer limit 20
--q1. what is the total revenue generated by male vs female customers ?
select gender, sum(purchase_amount) as revenue
from customer
group by gender

--q2. which customers used a discount but still spend more than the average purchase amount ?
select *
from customer
where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from customer)

--q3. which are the top 5 products with the highest average review rating
select item_purchased, round(avg(review_rating::numeric),2) as "average rating"
from customer
group by item_purchased
order by avg(review_rating) desc
Limit 5

--q4. compare the average purchase amounts between standard and express shipping
select shipping_type, round(avg(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type

--q5. do subcribed customers spend more ? compare average spend and total revenue between subcribers and non-subcribers
select subscription_status, count(customer_id) as total_customers, round(avg(purchase_amount),2) as avg_spend, sum(purchase_amount) as total_revenue
from customer
group by subscription_status

--q6. which 5 products have the highest precentage of purchase with discounts applied ?
select item_purchased,
round(100 * sum(case when discount_applied = 'Yes' then 1 else 0 end) / count(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5

--q7. segment customers into New, Returning, and Loya base on their total number of previous purchases and show the count of each segment
with customer_type as (
select customer_id, previous_purchases,
case 
	when previous_purchases = 1 then 'New' 
	when previous_purchases BETWEEN 2 AND 10 THEN 'Returning' 
	else 'Loyal' end as customer_segment
from customer
)

select customer_segment, count(*) as "number of customers"
from customer_type
group by customer_segment

--q8. what are the top 3 most purchased products within each category
with item_count as (
select category, item_purchased, count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer
group by category, item_purchased
)
select item_rank, category, item_purchased, total_orders
from item_count
where item_rank <= 3;

--q9. are customers who are repeat buyers (more than 5 previous purchases) also likely to subcribed ?
select subscription_status, count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status

--q10. what is the revenue contribution of each age group
select age_group, sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc